#!/bin/bash
# Pokrenite u: wp-content/plugins/sisari-rajac-v3/images/
# Ova verzija koristi browser User-Agent da zaobidje Wikimedia blokadu
# Usage: cd wp-content/plugins/sisari-rajac-v3/images && bash download-images-v2.sh

UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
REFERER="https://commons.wikimedia.org/"
BASE="https://upload.wikimedia.org/wikipedia/commons"
MIN_SIZE=10240  # 10KB minimum - manje je greška

dl(){
    local fname="$1"
    local url="$2"
    if [ -f "$fname" ] && [ "$(wc -c < "$fname")" -gt "$MIN_SIZE" ]; then
        echo "OK (vec postoji): $fname"
        return
    fi
    curl -s -L --max-time 60 \
        -H "User-Agent: $UA" \
        -H "Referer: $REFERER" \
        -H "Accept: image/webp,image/apng,image/*,*/*;q=0.8" \
        -H "Accept-Language: en-US,en;q=0.9" \
        -o "$fname" "$url"
    local size=$(wc -c < "$fname" 2>/dev/null || echo 0)
    if [ "$size" -gt "$MIN_SIZE" ]; then
        echo "OK ($size bytes): $fname"
    else
        echo "GREŠKA ($size bytes): $fname <- $url"
        rm -f "$fname"
    fi
    sleep 0.3
}

dl "Akademiepark_a_herd_of_Roe_Deer_(Capreolus_capreolus)_DSC_7111w.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Akademiepark_a_herd_of_Roe_Deer_%28Capreolus_capreolus%29_DSC_7111w.jpg?width=800"
dl "Apodemus_agrarius.jpg" "$BASE/thumb/0/06/Apodemus_agrarius.jpg/800px-Apodemus_agrarius.jpg"
dl "Apodemus_agrarius_2.jpg" "$BASE/thumb/6/6e/Apodemus_agrarius_2.jpg/800px-Apodemus_agrarius_2.jpg"
dl "Apodemus_flavicollis.jpg" "$BASE/thumb/b/b9/Apodemus_flavicollis.jpg/800px-Apodemus_flavicollis.jpg"
dl "Apodemus_flavicollis_2.jpg" "$BASE/thumb/0/0e/Apodemus_flavicollis_2.jpg/800px-Apodemus_flavicollis_2.jpg"
dl "Apodemus_flavicollis_neck.jpg" "$BASE/thumb/3/31/Apodemus_flavicollis_neck.jpg/800px-Apodemus_flavicollis_neck.jpg"
dl "Apodemus_sylvaticus.jpg" "$BASE/thumb/9/97/Apodemus_sylvaticus.jpg/800px-Apodemus_sylvaticus.jpg"
dl "Apodemus_sylvaticus_bosmuis.jpg" "$BASE/thumb/8/80/Apodemus_sylvaticus_bosmuis.jpg/800px-Apodemus_sylvaticus_bosmuis.jpg"
dl "Arctic_gray_wolf_(52360324811).jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Arctic_gray_wolf_%2852360324811%29.jpg?width=800"
dl "Aux_aguets_attentive_(906003479).jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Aux_aguets_attentive_%28906003479%29.jpg?width=800"
dl "Badger-badger.jpg" "$BASE/thumb/1/10/Badger-badger.jpg/800px-Badger-badger.jpg"
dl "Bank_Vole_Myodes_glareolus_Grand_Union_Canal_1.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Bank_Vole_Myodes_glareolus_Grand_Union_Canal_1.jpg?width=800"
dl "Bank_vole_(Myodes_glareolus).jpg" "$BASE/thumb/5/5a/Bank_vole_(Myodes_glareolus).jpg/800px-Bank_vole_(Myodes_glareolus).jpg"
dl "Brown_bear.jpg" "$BASE/thumb/6/6f/Brown_bear.jpg/800px-Brown_bear.jpg"
dl "Brown_bear_(Ursus_arctos_arctos)_running.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Brown_bear_%28Ursus_arctos_arctos%29_running.jpg?width=800"
dl "Canine_print.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Canine_print.jpg?width=800"
dl "Canis_aureus_-_golden_jackal.jpg" "$BASE/thumb/4/4e/Canis_aureus_-_golden_jackal.jpg/800px-Canis_aureus_-_golden_jackal.jpg"
dl "Canis_lupus_in_the_snow.jpg" "$BASE/thumb/8/8e/Canis_lupus_in_the_snow.jpg/800px-Canis_lupus_in_the_snow.jpg"
dl "Canis_lupus_laying.jpg" "$BASE/thumb/0/07/Canis_lupus_laying.jpg/800px-Canis_lupus_laying.jpg"
dl "Capreolus_capreolus_2.jpg" "$BASE/thumb/e/e6/Capreolus_capreolus_2.jpg/800px-Capreolus_capreolus_2.jpg"
dl "Chevreuil_roux.jpg" "$BASE/thumb/d/dc/Chevreuil_roux.jpg/800px-Chevreuil_roux.jpg"
dl "Clethrionomys_glareolus.jpg" "$BASE/thumb/e/ee/Clethrionomys_glareolus.jpg/800px-Clethrionomys_glareolus.jpg"
dl "Crocidura_leucodon-1.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Crocidura_leucodon-1.jpg?width=800"
dl "Crocidura_leucodon.jpg" "$BASE/thumb/2/2c/Crocidura_leucodon.jpg/800px-Crocidura_leucodon.jpg"
dl "Crocidura_leucodon_2.jpg" "$BASE/thumb/3/34/Crocidura_leucodon_2.jpg/800px-Crocidura_leucodon_2.jpg"
dl "Crocidura_suaveolens.jpg" "$BASE/thumb/d/db/Crocidura_suaveolens.jpg/800px-Crocidura_suaveolens.jpg"
dl "Crocidura_suaveolens_100694622.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Crocidura_suaveolens_100694622.jpg?width=800"
dl "Crocidura_suaveolens_2.jpg" "$BASE/thumb/f/f5/Crocidura_suaveolens_2.jpg/800px-Crocidura_suaveolens_2.jpg"
dl "Edible_dormouse_(Glis_glis).jpg" "$BASE/thumb/5/5a/Edible_dormouse_(Glis_glis).jpg/800px-Edible_dormouse_(Glis_glis).jpg"
dl "Ekorre_01.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Ekorre_01.jpg?width=800"
dl "Erinaceus_europaeus.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Erinaceus_europaeus.jpg?width=800"
dl "Erinaceus_europaeus_1.jpg" "$BASE/thumb/e/e3/Erinaceus_europaeus_1.jpg/800px-Erinaceus_europaeus_1.jpg"
dl "Erinaceus_roumanicus.jpg" "$BASE/thumb/7/75/Erinaceus_roumanicus.jpg/800px-Erinaceus_roumanicus.jpg"
dl "Erinaceus_roumanicus_spine_detail.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Erinaceus_roumanicus_spine_detail.jpg?width=800"
dl "Europaeischer_Iltis_Mustela_putorius.jpg" "$BASE/thumb/2/26/Europaeischer_Iltis_Mustela_putorius.jpg/800px-Europaeischer_Iltis_Mustela_putorius.jpg"
dl "European_Brown_Bear.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/European_Brown_Bear.jpg?width=800"
dl "European_wildcat_Nationalpark_Bayerischer_Wald_01.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/European_wildcat_Nationalpark_Bayerischer_Wald_01.jpg?width=800"
dl "Feldhase%2C_Lepus_europaeus_1a.JPG" "https://commons.wikimedia.org/wiki/Special:FilePath/Feldhase%2C_Lepus_europaeus_1a.JPG?width=800"
dl "Feldhase%2C_Lepus_europaeus_3a.JPG" "$BASE/thumb/4/4a/Feldhase%2C_Lepus_europaeus_3a.JPG/800px-Feldhase%2C_Lepus_europaeus_3a.JPG"
dl "Feldhase_Anfang_Mai.JPG" "https://commons.wikimedia.org/wiki/Special:FilePath/Feldhase_Anfang_Mai.JPG?width=800"
dl "Feldhase_Spur_Schnee.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Feldhase_Spur_Schnee.jpg?width=800"
dl "Felis_silvestris_felixi.jpg" "$BASE/thumb/1/10/Felis_silvestris_felixi.jpg/800px-Felis_silvestris_felixi.jpg"
dl "Felis_silvestris_silvestris.jpg" "$BASE/thumb/0/0e/Felis_silvestris_silvestris.jpg/800px-Felis_silvestris_silvestris.jpg"
dl "Foraging_Badger.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Foraging_Badger.jpg?width=800"
dl "Fox_portrait.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Fox_portrait.jpg?width=800"
dl "Fu%C3%9Fabdruck_Rotfuchs.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Fu%C3%9Fabdruck_Rotfuchs.jpg?width=800"
dl "Glis_glis_03.jpg" "$BASE/thumb/d/da/Glis_glis_03.jpg/800px-Glis_glis_03.jpg"
dl "Glis_glis_2.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Glis_glis_2.jpg?width=800"
dl "Golden_Jackal_Closeup.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Golden_Jackal_Closeup.jpg?width=800"
dl "Golden_Jackal_sa.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Golden_Jackal_sa.jpg?width=800"
dl "Golden_jackal_-_portrait.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Golden_jackal_-_portrait.jpg?width=800"
dl "Golden_jackal_at_Keoladeo_Ghana_National_Park.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Golden_jackal_at_Keoladeo_Ghana_National_Park.jpg?width=800"
dl "Golden_jackal_cub.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Golden_jackal_cub.jpg?width=800"
dl "Hare_tracks_in_snow.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Hare_tracks_in_snow.jpg?width=800"
dl "Hazel_dormouse.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Hazel_dormouse.jpg?width=800"
dl "Hedgehog_footprint.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Hedgehog_footprint.jpg?width=800"
dl "Hedgehog_in_garden.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Hedgehog_in_garden.jpg?width=800"
dl "Least_Weasel_%28Mustela_nivalis%29.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Least_Weasel_%28Mustela_nivalis%29.jpg?width=800"
dl "Least_weasel.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Least_weasel.jpg?width=800"
dl "Lutra_lutra.jpg" "$BASE/thumb/c/ce/Lutra_lutra.jpg/800px-Lutra_lutra.jpg"
dl "Lutra_lutra_2.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Lutra_lutra_2.jpg?width=800"
dl "Martes_foina_1.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Martes_foina_1.jpg?width=800"
dl "Martes_foina_4.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Martes_foina_4.jpg?width=800"
dl "Martes_foina_MHNT.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Martes_foina_MHNT.jpg?width=800"
dl "Martes_foina_ct.jpg" "$BASE/thumb/0/09/Martes_foina_ct.jpg/800px-Martes_foina_ct.jpg"
dl "Martes_foina_white_throat.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Martes_foina_white_throat.jpg?width=800"
dl "Martes_martes-08-WA-Jochen.jpg" "$BASE/thumb/c/cd/Martes_martes-08-WA-Jochen.jpg/800px-Martes_martes-08-WA-Jochen.jpg"
dl "Martes_martes_2_%28Stephan_Morris%29.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Martes_martes_2_%28Stephan_Morris%29.jpg?width=800"
dl "Martes_martes_crop.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Martes_martes_crop.jpg?width=800"
dl "Martes_martes_in_Sweden.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Martes_martes_in_Sweden.jpg?width=800"
dl "Martes_martes_on_tree.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Martes_martes_on_tree.jpg?width=800"
dl "Martes_martes_throat.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Martes_martes_throat.jpg?width=800"
dl "Meles_meles_-_British_Wildlife_Centre_%281%29.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Meles_meles_-_British_Wildlife_Centre_%281%29.jpg?width=800"
dl "Meles_meles_-_Sett.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Meles_meles_-_Sett.jpg?width=800"
dl "Meles_meles_face.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Meles_meles_face.jpg?width=800"
dl "Meles_meles_Усть-Каменогорск.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Meles_meles_%D0%A3%D1%81%D1%82%D1%8C-%D0%9A%D0%B0%D0%BC%D0%B5%D0%BD%D0%BE%D0%B3%D0%BE%D1%80%D1%81%D0%BA.jpg?width=800"
dl "Microtus_arvalis.jpg" "$BASE/thumb/f/f2/Microtus_arvalis.jpg/800px-Microtus_arvalis.jpg"
dl "Microtus_arvalis_2.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Microtus_arvalis_2.jpg?width=800"
dl "Microtus_arvalis_walks.JPG" "https://commons.wikimedia.org/wiki/Special:FilePath/Microtus_arvalis_walks.JPG?width=800"
dl "Microtus_subterraneus.jpg" "$BASE/thumb/c/c9/Microtus_subterraneus.jpg/800px-Microtus_subterraneus.jpg"
dl "Microtus_subterraneus_2.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Microtus_subterraneus_2.jpg?width=800"
dl "Microtus_subterraneus_I.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Microtus_subterraneus_I.jpg?width=800"
dl "Muscardinus_avellanarius.jpg" "$BASE/thumb/2/2e/Muscardinus_avellanarius.jpg/800px-Muscardinus_avellanarius.jpg"
dl "Muscardinus_avellanarius_1.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Muscardinus_avellanarius_1.jpg?width=800"
dl "Muscardinus_avellanarius_7.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Muscardinus_avellanarius_7.jpg?width=800"
dl "Mustela_nivalis_-British_Wildlife_Centre-_edit.jpg" "$BASE/thumb/d/d7/Mustela_nivalis_-British_Wildlife_Centre-_edit.jpg/800px-Mustela_nivalis_-British_Wildlife_Centre-_edit.jpg"
dl "Mustela_nivalis_-_weasel.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Mustela_nivalis_-_weasel.jpg?width=800"
dl "Mustela_nivalis_upright.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Mustela_nivalis_upright.jpg?width=800"
dl "Mustela_putorius.jpg" "$BASE/thumb/7/79/Mustela_putorius.jpg/800px-Mustela_putorius.jpg"
dl "Mustela_putorius_-_Vrancea%2C_Romania.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Mustela_putorius_-_Vrancea%2C_Romania.jpg?width=800"
dl "Mustela_putorius_01.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Mustela_putorius_01.jpg?width=800"
dl "Myodes_glareolus.jpg" "$BASE/thumb/2/24/Myodes_glareolus.jpg/800px-Myodes_glareolus.jpg"
dl "Myodes_glareolus2.JPG" "https://commons.wikimedia.org/wiki/Special:FilePath/Myodes_glareolus2.JPG?width=800"
dl "Myotis_myotis_head.jpg" "$BASE/thumb/2/2a/Myotis_myotis_head.jpg/800px-Myotis_myotis_head.jpg"
dl "Mysz_polna,_PL.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Mysz_polna%2C_PL.jpg?width=800"
dl "Nannospalax_leucodon.jpg" "$BASE/thumb/6/60/Nannospalax_leucodon.jpg/800px-Nannospalax_leucodon.jpg"
dl "Neomys_fodiens.jpg" "$BASE/thumb/d/d1/Neomys_fodiens.jpg/800px-Neomys_fodiens.jpg"
dl "Neomys_fodiens_2.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Neomys_fodiens_2.jpg?width=800"
dl "Neomys_fodiens_TF_090829.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Neomys_fodiens_TF_090829.jpg?width=800"
dl "Neugieriges_Mauswiesel.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Neugieriges_Mauswiesel.jpg?width=800"
dl "Nyctalus_noctula_01.jpg" "$BASE/thumb/7/74/Nyctalus_noctula_01.jpg/800px-Nyctalus_noctula_01.jpg"
dl "Putorius_putorius_Sturm.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Putorius_putorius_Sturm.jpg?width=800"
dl "Red_Fox_(Vulpes_vulpes)_(4).jpg" "$BASE/thumb/a/a9/Red_Fox_(Vulpes_vulpes)_(4).jpg/800px-Red_Fox_(Vulpes_vulpes)_(4).jpg"
dl "Red_fox_at_Gamla.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Red_fox_at_Gamla.jpg?width=800"
dl "Red_fox_kit_3_(Vulpes_vulpes).jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Red_fox_kit_3_%28Vulpes_vulpes%29.jpg?width=800"
dl "Red_fox_snout.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Red_fox_snout.jpg?width=800"
dl "Red_squirrel_Sciurus_vulgaris_Istria.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Red_squirrel_Sciurus_vulgaris_Istria.jpg?width=800"
dl "Rhinolophus_ferrumequinum.jpg" "$BASE/thumb/d/d7/Rhinolophus_ferrumequinum.jpg/800px-Rhinolophus_ferrumequinum.jpg"
dl "Rhinolophus_hipposideros_-_Gzenyme.jpg" "$BASE/thumb/7/7f/Rhinolophus_hipposideros_-_Gzenyme.jpg/800px-Rhinolophus_hipposideros_-_Gzenyme.jpg"
dl "Roe_deer_(Capreolus_capreolus).jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Roe_deer_%28Capreolus_capreolus%29.jpg?width=800"
dl "Roe_deer_male_kitz1.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Roe_deer_male_kitz1.jpg?width=800"
dl "Sciurus_vulgaris_07.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Sciurus_vulgaris_07.jpg?width=800"
dl "Sciurus_vulgaris_Narew.jpg" "$BASE/thumb/f/f5/Sciurus_vulgaris_Narew.jpg/800px-Sciurus_vulgaris_Narew.jpg"
dl "Sorex-araneus.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Sorex-araneus.jpg?width=800"
dl "Sorex_araneus.jpg" "$BASE/thumb/e/e5/Sorex_araneus.jpg/800px-Sorex_araneus.jpg"
dl "Sorex_araneus_2.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Sorex_araneus_2.jpg?width=800"
dl "Sorex_minutus.jpg" "$BASE/thumb/a/ae/Sorex_minutus.jpg/800px-Sorex_minutus.jpg"
dl "Sorex_minutus_crop.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Sorex_minutus_crop.jpg?width=800"
dl "Sorex_minutus_palm.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Sorex_minutus_palm.jpg?width=800"
dl "Spalax_leucodon.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Spalax_leucodon.jpg?width=800"
dl "Speicherkoog_Lepus_europaeus.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Speicherkoog_Lepus_europaeus.jpg?width=800"
dl "Steinmarder-2007-Asio.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Steinmarder-2007-Asio.jpg?width=800"
dl "Sus_scrofa_head.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Sus_scrofa_head.jpg?width=800"
dl "Sus_scrofa_in_a_field.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Sus_scrofa_in_a_field.jpg?width=800"
dl "Sus_scrofa_scrofa.jpg" "$BASE/thumb/b/b0/Sus_scrofa_scrofa.jpg/800px-Sus_scrofa_scrofa.jpg"
dl "Sus_scrofa_young.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Sus_scrofa_young.jpg?width=800"
dl "Talpa_europaea.jpg" "$BASE/thumb/f/f7/Talpa_europaea.jpg/800px-Talpa_europaea.jpg"
dl "Talpa_europaea_2.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Talpa_europaea_2.jpg?width=800"
dl "Talpa_europaea_MHNT.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Talpa_europaea_MHNT.jpg?width=800"
dl "Ursus_arctos_Björnen.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Ursus_arctos_Bj%C3%B6rnen.jpg?width=800"
dl "Ursus_arctos_arctos.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Ursus_arctos_arctos.jpg?width=800"
dl "Vulpes_Vulpes_in_snow.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Vulpes_Vulpes_in_snow.jpg?width=800"
dl "Wachsamer_Feldhase_in_Birkholz_bei_Bernau.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Wachsamer_Feldhase_in_Birkholz_bei_Bernau.jpg?width=800"
dl "Westelijke_blindmuis_-_Lesser_Blind_Mole-rat_-_Nannospalax_leucodon.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Westelijke_blindmuis_-_Lesser_Blind_Mole-rat_-_Nannospalax_leucodon.jpg?width=800"
dl "Whiskers_(30452296398).jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Whiskers_%2830452296398%29.jpg?width=800"
dl "Wild_Boar_Sow_and_Piglets.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Wild_Boar_Sow_and_Piglets.jpg?width=800"
dl "Wildcat_on_a_tree.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Wildcat_on_a_tree.jpg?width=800"
dl "Wood_mouse_(Apodemus_sylvaticus).jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Wood_mouse_%28Apodemus_sylvaticus%29.jpg?width=800"
dl "Тхір_лісовий.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/%D0%A2%D1%85%D1%96%D1%80_%D0%BB%D1%96%D1%81%D0%BE%D0%B2%D0%B8%D0%B9.jpg?width=800"
dl "Siebenschläfer_auf_Baum.JPG" "https://commons.wikimedia.org/wiki/Special:FilePath/Siebenschl%C3%A4fer_auf_Baum.JPG?width=800"

echo ""
echo "=== Završeno ==="
echo "Uspešno preuzete slike (>10KB):"
find . -name "*.jpg" -o -name "*.JPG" | xargs -I{} sh -c '[ "$(wc -c < "{}")" -gt 10240 ] && echo "{}"' 2>/dev/null | wc -l
echo ""
echo "Neuspešno (nedostaju):"
find . -name "*.jpg" -o -name "*.JPG" | xargs -I{} sh -c '[ "$(wc -c < "{}")" -le 10240 ] && echo "{}"' 2>/dev/null
